@api = http://localhost:3700

###
POST {{api}}/registrar/estudiante
Content-Type: application/json

{
  "nombre": "Valentina",
  "apellido": "Mamani",
  "ci": "1234567-CB",
  "fecha_nacimiento": "2015-03-22",
  "genero": "F",
  "direccion": "Calle Sucre #345, Cochabamba",
  "telefono": "76543210",
  "email_personal": "vale.mamani@gmail.com",
  "nacionalidad": "Boliviana",
  "estado_civil": null,
  "correo": "valentina.mamani@estudiante.colegio.edu.bo",
  "password": "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
  "tipo_sangre": "A+",
  "alergias": "Polen, polvo",
  "condiciones_medicas": "Asma leve",
  "medicamentos": "Inhalador salbutamol",
  "seguro_medico": "Seguro Privado Boliviano",
  "numero_hermanos": 2,
  "posicion_hermanos": 1,
  "vive_con": "Ambos padres",
  "necesidades_especiales": null,
  "transporte": "Escolar",
  "id_grado": 9,
  "tipo_inscripcion": "Nueva",
  "colegio_procedencia": null,
  "motivo_traslado": null,
  "monto_matricula": 500,
  "descuento_matricula": 0,
  "tipo_estudiante": "Regular",
  "requiere_apoyo": 0,
  "observaciones": "Estudiante nueva inscripción 2026",
  "usuario_registra": 1,

  "tutor1": {
    "nombre": "Jorge",
    "apellido": "Mamani",
    "ci": "4567890",
    "fecha_nacimiento": "1978-11-10",
    "genero_persona": "M",
    "direccion": "Calle Sucre #345, Cochabamba",
    "telefono": "71234567",
    "email_personal": "jorge.mamani@gmail.com",
    "nacionalidad": "Boliviana",
    "estado_civil": "Casado",
    "correo": "jorge.mamani@gmail.com",
    "password": "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    "genero_padre": "M",
    "ocupacion": "Médico",
    "lugar_trabajo": "Hospital Viedma",
    "telefono_trabajo": "44221133",
    "nivel_educativo": "Doctorado",
    "ingreso_mensual": 9500,
    "parentesco": "Padre",
    "es_responsable_economico": 1,
    "es_contacto_emergencia": 1,
    "puede_retirar": 1,
    "vive_con_estudiante": 1
  },

  "tutor2": {
    "nombre": "Rosa",
    "apellido": "Torrez",
    "ci": "5678901",
    "fecha_nacimiento": "1981-06-25",
    "genero_persona": "F",
    "direccion": "Calle Sucre #345, Cochabamba",
    "telefono": "72345678",
    "email_personal": "rosa.torrez@gmail.com",
    "nacionalidad": "Boliviana",
    "estado_civil": "Casada",
    "correo": "rosa.torrez@gmail.com",
    "password": "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    "genero_padre": "F",
    "ocupacion": "Arquitecta",
    "lugar_trabajo": "Estudio de Arquitectura BTR",
    "telefono_trabajo": "44332211",
    "nivel_educativo": "Licenciatura",
    "ingreso_mensual": 7200,
    "parentesco": "Madre",
    "es_responsable_economico": 1,
    "es_contacto_emergencia": 1,
    "puede_retirar": 1,
    "vive_con_estudiante": 1
  }
}